version: '3.8'
services:
      localdb:
        container_name: mysql8
        image: mysql:latest
        ports:
          - '3312:3306'
        volumes:
          - ./var/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: webflux_test
          MYSQL_USER: sa
          MYSQL_PASSWORD: sa
