spring:
    r2dbc:
        url: r2dbc:mysql://localhost:3312/webflux_test
        username: sa
        password: sa
    flyway:
        url: jdbc:mysql://localhost:3312/webflux_test
        user: ${spring.r2dbc.username}
        password: ${spring.r2dbc.password}
        baseline-on-migrate: true
